### ISSUE TITLE
Can you publish all your softs/libs in your GitHub account?

### ISSUE THREAD

**Issue by Neustradamus** [s-vincent/kernel-modules#1]
Dear Mister Vincent,

Thanks for your contribution in OpenSource world.

Can you publish all your softs/libs in your GitHub account?
- https://sourceforge.net/u/s-vincent/profile/

I do one only example but it is not the only one:
- rdnssd-win32

Thanks in advance.

Regards,

Neustradamus

**Comment by s-vincent** [comment]
Not related to kernel-modules. project.

**Comment by Neustradamus** [comment]
@s-vincent: Yes but not easy to contact you.

Can you add your projects in https://github.com/s-vincent?

- https://sourceforge.net/projects/rdnssd-win32/
- https://sourceforge.net/projects/ipv6-updater/
- https://sourceforge.net/projects/xjplayer/
- https://sourceforge.net/projects/jsonrpc-cpp/

- https://sourceforge.net/projects/pepperspot/
- https://sourceforge.net/projects/turnserver/

- https://sourceforge.net/projects/fmipv6/
- https://sourceforge.net/projects/libsystools/

Thanks in advance.

**Comment by s-vincent** [comment]
OK everything is migrated except fmipv6 and libsystools because I was just contributors on that ones (i.e. I am not the owner).

Please note that:
- these projects are migrated as is and may probably not compile or run correctly ;
- these projects are considered archives for me so I will not work on them anymore.

Regards.

**Comment by Neustradamus** [comment]
@s-vincent: Thanks a lot!
Can you add on sourceforge projects that the code has moved (like a lot of projects)?
